linter:
  rules:
    avoid_positional_boolean_parameters: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    prefer_interpolation_to_compose_strings: false
    sort_constructors_first: false
    use_string_buffers: false
    no_default_cases: false
    avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    public_member_api_docs: true

formatter:
  trailing_commas: preserve
